Frontend/factories
loernwerk/loernwerk pull request #15
Opened 2023-07-04 19:36 UTC by gh-phobion

2023-07-05 07:51 UTC, Kr0nox requested changes
All Content objects need their type set. I would suggest adding a constructor for that,

Use @inheritedoc in the child classes

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/ContentFactory.ts
> +    return contentObject;
Juat return them directly in the switch and throw an error if we cant find a fitting type in the switch

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/ContentFactory.ts
> +   * @param json the JSON sent by the Webserver
I would not specify that this json was sent by the webserver, since these factories function independently of the webserver

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/ContentFactory.ts
> +   * @param json the JSON sent by the Webserver
same here with the webserver

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/EmbedContentFactory.ts
> +    return embedContent;
they all need there type set too.
The best thing would be if you added a constructor for all of them that sets their own type wo the coresponding Value

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/EmbedContentFactory.ts
> +   * @protected
use @inheritedoc

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/H5PContentFactory.ts
> +   * @returns the h5pContent as H5PContent type
use @inheritedoc

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/H5PContentFactory.ts
> +    h5pContent.h5pContentId = (json as H5PContent).h5pContentId;
contenttype set again

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/ImageContentFactory.ts
> +   * @returns the imageContent as ImageContent type
use @inheritedoc

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/ImageContentFactory.ts
> +    imageContent.scale = (json as ImageContent).scale;
type again

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +   * @returns the textContent as TextContent type
use @inheritedoc

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +    textContent.alignmentHorizontal = (json as TextContent).alignmentHorizontal;
type again

2023-07-05 07:51 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +    textContent.textSnippets = (json as TextContent).textSnippets;
this should be deep copied, so a for loop for every snippet in the json so that you can also copy each TextOption

2023-07-05 07:54 UTC, c0derMo commented
Also, this PR should probably add using the Factory inside the RestInterface where specified earlier - just iterate over the `content` map and throw every value into the factory, and save it back to the map

2023-07-08 21:04 UTC, c0derMo approved these changes

2023-07-09 09:52 UTC, Kr0nox requested changes

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/EmbedContentFactory.ts
> +   * @returns the buildContent as BuildContent type
should this say embed conten?

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/H5PContentFactory.ts
> +   * @returns the h5pContent as H5PContent type
what is `the h5pContent`?

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/ImageContentFactory.ts
> +   * @returns the imageContent as ImageContent type
what is `the imageContent`?

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +   * @returns the textContent as TextContent type
what is `the textContent`?

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +    (json as TextContent).textSnippets.forEach((snippet) => {
is this ass really needed? we should be able to iterate over the json object shouldnt we?

2023-07-09 09:52 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +      textContent.textSnippets.push(Object.assign({}, snippet));
make sure this creates a propper textOptions object

2023-07-12 13:42 UTC, c0derMo requested changes
Also, I think the factories are in the wrong directory, they should be in the `src/factories` directory, I think that was also wrong somewhere in our document 😂

2023-07-12 13:42 UTC, c0derMo commented on frontend/frame/ContentFactory.ts
> +        throw new Error(`Not supported content type ${(json as Content).type}`);
Maybe throw a loernwerk error here

2023-07-13 10:13 UTC, Kr0nox commented on frontend/frame/ImageContentFactory.ts
> +   * @returns the imageContent as ImageContent type
write `the json` instead and leave type out

2023-07-13 10:13 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +   * @returns the textContent as TextContent type
write the json instead and leave type out

2023-07-13 10:15 UTC, Kr0nox commented on frontend/frame/H5PContentFactory.ts
> +   * @returns the h5pContent as H5PContent type
write `the json as a H5PContent` instead

2023-07-13 10:15 UTC, Kr0nox commented on frontend/frame/ImageContentFactory.ts
> +   * @returns the imageContent as ImageContent type
write `the json as a H5PContent` instead

2023-07-13 10:15 UTC, Kr0nox commented on frontend/frame/TextContentFactory.ts
> +   * @returns the textContent as TextContent type
write `the json as a H5PContent` instead

2023-07-16 14:48 UTC, Kr0nox commented
@gh-phobion once the build error is fixed this can be merged

2023-07-16 19:34 UTC, c0derMo approved these changes

2023-07-16 20:39 UTC, Kr0nox approved these changes

2023-07-17 06:32 UTC, merged