Imprint & Other improvements #2
loernwerk/loernwerk pull request #21
Opened 2023-07-09 17:46 UTC by c0derMo

This PR bundles a handful of small improvements to the platform, namely:

- The ability to add a custom imprint to the site
- Deletion of H5P Content upon Sequence deletion
- Added correct translation of the H5P error messages
- Speeding up several database queries by only selecting needed fields

2023-07-10 08:08 UTC, ProgramPhoenix approved these changes

2023-07-13 10:12 UTC, Kr0nox requested changes

2023-07-13 10:12 UTC, Kr0nox commented on README.md
> +To add your own imprint, edit the `build/dist/imprint.html` file.
add that the file can also be changed in the sources

2023-07-13 13:37 UTC, Kr0nox approved these changes

2023-07-14 12:23 UTC, merged