Frontend/NavBar
loernwerk/loernwerk pull request #24
Opened 2023-07-11 19:18 UTC by c0derMo

This PR adds the Navigation bar to all views that need it.

Since a lot of the views that need this are still WIP, this PR will stay as a draft until they are all finished.
These Views include:
- [ ] SequenceOverviewView
- [ ] AccountView
- [ ] SequenceEditView
- [ ] AdminView

Since this PR is also dependent on all the views, it will also change the import of Views in the router so that's production ready.

2023-07-13 13:44 UTC, Kr0nox requested changes

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +    <ButtonComponent
Use RouterLinks

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +    <img src="../assets/Logo.png" class="h-full mr-5" />
I think we should use a different version of the Logo without the background, I will provide you with it

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +  <div class="w-full h-20 bg-gray-300 flex flex-row items-center gap-5">
I think we either need a different color  or add a dropshadow

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +  <div class="w-full h-20 bg-gray-300 flex flex-row items-center gap-5">
specifie colors in the tailwind config like the others

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +.selected-menu-item {
use tailwind classes directly (if you dont want to repeat them write a NavBarLinkComponent)

2023-07-13 13:44 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +    <ButtonComponent
From a general style guide you wouldnt style navbar items like that

2023-07-17 16:22 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +    <img src="../assets/Logo.png" class="h-full mr-5" />
I uploaded a glow and a not glowng version. I have not yet implemented that yet. we should do that based on the final design and see what looks better

2023-07-18 17:56 UTC, c0derMo commented
PR is ready for review @Kr0nox @loernwerk/active

2023-07-18 18:16 UTC, ProgramPhoenix approved these changes
lgtm

2023-07-18 18:22 UTC, Kr0nox requested changes

2023-07-18 18:22 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +      currentViewLocalized.value = 'Account';
I would not add Account since its item is the icon on the right

2023-07-18 18:22 UTC, Kr0nox commented on frontend/src/components/NavigationBar.vue
> +    <NavigationBarItem v-if="currentViewLocalized !== ''" :active="true">
imo it feels more natural to have this between the overview and admin view

2023-07-18 18:22 UTC, Kr0nox commented on frontend/src/components/NavigationBarItem.vue
> +    :class="{ italic: active, 'font-bold': active }"
I think the italic is to much

2023-07-18 18:22 UTC, Kr0nox commented on frontend/src/components/NavigationBarItem.vue
> +    class="text-2xl select-none"
whte font

2023-07-18 18:22 UTC, Kr0nox commented on frontend/src/components/NavigationBarItem.vue
> +  targetLink: {
doc

2023-07-18 18:43 UTC, Kr0nox approved these changes

2023-07-18 18:43 UTC, merged