Configuration
loernwerk/loernwerk pull request #31
Opened 2023-07-18 17:25 UTC by Kr0nox

This draft is used as a cheklist for what needs to be implemented. @loernwerk/active please check of what is already done

- [ ] router
- [ ] controller: changing and reading configs
- [ ] UI for changing configs

- [ ] Maximale Sequenz Zahl frontend
- [ ] Maximale Sequenz Zahl backend
- [ ] Maximale Slide Zahl frontend
- [ ] Maximale Slide Zahl backend

2023-07-19 17:06 UTC, a-bumblebee approved these changes

2023-07-19 17:23 UTC, c0derMo requested changes

2023-07-19 17:23 UTC, c0derMo commented on backend/controller/ConfigController.ts
> +        return await DBConfigEntry.findOneBy({ key: key });
This should check whether the config key exists - even if that's guaranteed by ensureConfig, I feel like this should throw an error if no config entry can be found

2023-07-19 17:23 UTC, c0derMo commented on backend/controller/ConfigController.ts
> +        entry.save();
missing await

2023-07-19 17:23 UTC, c0derMo commented on backend/controller/ConfigController.ts
> +        return await DBConfigEntry.findOneBy({ key: key });
Also, this should only return the value, not the entire DBConfigEntry

2023-07-19 17:23 UTC, c0derMo commented on backend/controller/SequenceController.ts
> +        if (sequencesOfUser.length >= userSequenceLimit) {
This also needs to check if sequenceUserLimit > 0

2023-07-19 17:23 UTC, c0derMo commented on backend/controller/SequenceController.ts
> +            sequenceSlideCount >= userSlideLimit
This also needs to check if userSlideLimit > 0

2023-07-19 17:23 UTC, c0derMo commented on backend/router/ConfigRouterFactory.ts
> +                res.status(200).json(value);
This should send `{ value }`

2023-07-19 17:23 UTC, c0derMo commented on frontend/src/components/admin/ConfigEditor.vue
> +  config: {
Per design, this is called `entries`

2023-07-19 17:23 UTC, c0derMo commented on frontend/src/components/admin/ConfigEditor.vue
> +        type.options[0] == 'limited' &&
What is this for exactly?

2023-07-19 17:23 UTC, c0derMo commented on model/configuration/IConfigType.ts
> +export type NumberOption = 'limited' | 'unlimited';
Where is this used?

2023-07-20 07:16 UTC, ProgramPhoenix approved these changes

2023-07-20 07:43 UTC, c0derMo commented on frontend/src/components/admin/ConfigEditor.vue
> +        type.options[0] == 'limited' &&
@Kr0nox since I think you wrote this

2023-07-20 08:41 UTC, c0derMo approved these changes

2023-07-20 08:42 UTC, ProgramPhoenix approved these changes

2023-07-20 08:42 UTC, merged