better errors
loernwerk/loernwerk pull request #66
Opened 2023-08-20 07:38 UTC by ProgramPhoenix

Errors are currently improved in:

- AccountController
- LoginView
- AccountCreationContainer
- AccountDetailsEditContainer

2023-08-22 20:09 UTC, ProgramPhoenix commented
this pr is also ready for review now

2023-08-23 05:17 UTC, Kr0nox requested changes
For me the toast get displayed outside of the screen (what I did was login, then turn of the backend and click to edit an existing sequence. I get redirected to the edit screen, but as expected an error occured. The Toast was then dislpayed outside of the screen to most parts)

In addition stylewise, I would not make the whole toast red but rather just the border and the timer and have the rest in a default color

2023-08-23 05:17 UTC, Kr0nox commented on backend/controller/AccountController.ts
> +                LoernwerkErrorMessages.USER_NOT_FOUND,
I dont think user not found is the right thing here, It should rather say something like `username or password is incorrect`

2023-08-23 05:17 UTC, Kr0nox commented on backend/controller/AccountController.ts
> +                LoernwerkErrorMessages.USER_NOT_FOUND,
Same as above

2023-08-23 08:11 UTC, ProgramPhoenix commented
things are fixed. since errors should not occure often, i would prefer a more eye catching design. what do you think @c0derMo @a-bumblebee @gh-phobion ?

2023-08-23 08:22 UTC, c0derMo commented
I'm personally fine with either version, what we can do as a compromise maybe would be making the toast background lighter (something like `bg-red-500` or `bg-red-400`), that way it's closer to a "default color", but still eye-catching I'd guess

2023-08-23 08:24 UTC, c0derMo requested changes

2023-08-23 08:24 UTC, c0derMo commented on frontend/src/components/ErrorCatcher.vue
> +  console.log(errormessages.value);
Also noticed these console.log's which might need to be removed

2023-08-23 08:24 UTC, c0derMo commented on frontend/src/views/LogInView.vue
> +      console.log(e.message);
Another one

2023-08-23 12:35 UTC, c0derMo requested changes

2023-08-23 12:35 UTC, c0derMo commented on frontend/src/components/ErrorCatcher.vue
> +  console.log('this needed to be displayed, err:' + err + ' info: ' + info);
another one

2023-08-23 13:01 UTC, Kr0nox reviewed
The width of the toasts should be increased, since text can get cut of.
I would also increase the time, since its barely possible to read a toast

2023-08-24 08:19 UTC, c0derMo approved these changes

2023-08-24 12:09 UTC, Kr0nox approved these changes

2023-08-24 12:15 UTC, merged